// Canonical NPGX A-Z Roster — 26 Ninja Punk Girls
// Client-safe (no fs). Single source of truth for character data across all pages.

export interface NPGXCharacter {
  letter: string;          // A-Z
  slug: string;            // URL-friendly identifier
  name: string;            // Display name
  katakana: string;        // Japanese katakana name
  token: string;           // $TICKER
  tagline: string;         // One-line description
  category: 'cyberpunk' | 'stealth' | 'gothic' | 'elemental' | 'mecha' | 'arcane' | 'street' | 'kawaii';
  description: string;     // Longer bio
  specialties: string[];   // 3 key abilities
  image: string;           // Primary avatar path
  hasImages: boolean;      // Whether real images exist in public/
  site?: string;           // External site URL if exists
}

export const NPGX_ROSTER: NPGXCharacter[] = [
  {
    letter: 'A',
    slug: 'aria-voidstrike',
    name: 'Aria Kurosawa Voidstrike',
    katakana: 'アリア・クロサワ・ヴォイドストライク',
    token: '$ARIA',
    tagline: 'The most dangerous woman you\'ll ever want',
    category: 'cyberpunk',
    description: 'Seductive hacker who uses her beauty as a weapon. She gets inside your head before she gets inside your system.',
    specialties: ['seduction', 'hacking', 'infiltration'],
    image: '/content/aria-voidstrike/images/avatar/aria-voidstrike-confrontational.png',
    hasImages: true,
  },
  {
    letter: 'B',
    slug: 'blade-nightshade',
    name: 'Blade Kageyama Nightshade',
    katakana: 'ブレイド・カゲヤマ・ナイトシェイド',
    token: '$BLADE',
    tagline: 'Silent assassin with poison-edge katanas',
    category: 'stealth',
    description: 'Master assassin trained in the underground fight pits of Neo-Tokyo. Her twin katanas are laced with synthetic neurotoxin.',
    specialties: ['dual katanas', 'poison arts', 'silent takedowns'],
    image: '/content/blade-nightshade/images/avatar/blade-nightshade-avatar.png',
    hasImages: true,
  },
  {
    letter: 'C',
    slug: 'cherryx',
    name: 'CherryX',
    katakana: 'チェリーX',
    token: '$CHERRYX',
    tagline: 'Kawaii punk with street graffiti powers',
    category: 'street',
    description: 'Kawaii meets punk rock. Petite 28yo AI model with pink hair, chest tattoos, and a street-graffiti aesthetic. Pay-to-mint tokenized content on Bitcoin with a chaos-engine video player.',
    specialties: ['street art', 'tokenized content', 'chaos engine'],
    image: '/content/cherryx/images/avatar/cherryx-avatar.png',
    hasImages: true,
    site: 'https://cherryx.space',
  },
  {
    letter: 'D',
    slug: 'dahlia-ironveil',
    name: 'Dahlia Hagiwara Ironveil',
    katakana: 'ダリア・ハギワラ・アイアンヴェイル',
    token: '$DAHLIA',
    tagline: 'Kawaii on the outside. Chaos on the inside.',
    category: 'kawaii',
    description: 'Harajuku kawaii-punk queen. Pink bows, PVC, fisheye selfies, zero limits. Runs with Trix and Echo.',
    specialties: ['kawaii chaos', 'Harajuku fashion', 'provocation'],
    image: '/content/dahlia-ironveil/images/avatar/dahlia-ironveil-avatar.png',
    hasImages: true,
  },
  {
    letter: 'E',
    slug: 'echo-neonflare',
    name: 'Echo Fujimori Neonflare',
    katakana: 'エコー・フジモリ・ネオンフレア',
    token: '$ECHO',
    tagline: 'Cyber DJ who weaponizes sound waves',
    category: 'cyberpunk',
    description: 'Underground DJ turned sonic warrior. Her custom decks generate frequencies that can shatter glass, disrupt electronics, or hypnotize crowds.',
    specialties: ['sonic warfare', 'crowd control', 'frequency manipulation'],
    image: '/content/echo-neonflare/images/avatar/echo-neonflare-avatar.png',
    hasImages: true,
  },
  {
    letter: 'F',
    slug: 'fury-steelwing',
    name: 'Fury Takahashi Steelwing',
    katakana: 'フューリー・タカハシ・スティールウィング',
    token: '$FURY',
    tagline: 'Mecha pilot with fused neural interface',
    category: 'mecha',
    description: 'Her nervous system is permanently bonded to a combat exosuit. The suit is alive, and together they are unstoppable.',
    specialties: ['mecha combat', 'neural sync', 'aerial assault'],
    image: '/content/fury-steelwing/images/avatar/fury-steelwing-avatar.png',
    hasImages: true,
  },
  {
    letter: 'G',
    slug: 'ghost-razorthorn',
    name: 'Ghost Kagemaru Razorthorn',
    katakana: 'ゴースト・カゲマル・レイザーソーン',
    token: '$GHOST',
    tagline: 'Invisible predator with thorn-blade gauntlets',
    category: 'stealth',
    description: 'No one has ever seen her face. She strikes from total invisibility using thorned gauntlets that shred through any material.',
    specialties: ['total invisibility', 'thorn blades', 'predator instinct'],
    image: '/content/ghost-razorthorn/images/avatar/ghost-razorthorn-avatar.png',
    hasImages: true,
  },
  {
    letter: 'H',
    slug: 'hex-crimsonwire',
    name: 'Hex Nakamura Crimsonwire',
    katakana: 'ヘクス・ナカムラ・クリムゾンワイヤー',
    token: '$HEX',
    tagline: 'Techno-witch who codes spells in binary',
    category: 'arcane',
    description: 'Half-hacker, half-sorceress. She writes enchantments as executable code. Her crimson wires are both circuits and spell-threads.',
    specialties: ['tech sorcery', 'binary enchantments', 'wire manipulation'],
    image: '/content/hex-crimsonwire/images/avatar/hex-crimsonwire-avatar.png',
    hasImages: true,
  },
  {
    letter: 'I',
    slug: 'ivy-darkpulse',
    name: 'Ivy Midorikawa Darkpulse',
    katakana: 'アイヴィー・ミドリカワ・ダークパルス',
    token: '$IVY',
    tagline: 'Bio-hacker with living cybernetic vines',
    category: 'cyberpunk',
    description: 'Genetic engineer who spliced plant DNA with nanotech. Her body grows living circuits that can interface with any system.',
    specialties: ['bio-hacking', 'living circuits', 'system override'],
    image: '/content/ivy-darkpulse/images/avatar/ivy-darkpulse-avatar.png',
    hasImages: true,
  },
  {
    letter: 'J',
    slug: 'jinx-shadowfire',
    name: 'Jinx Matsuda Shadowfire',
    katakana: 'ジンクス・マツダ・シャドウファイア',
    token: '$JINX',
    tagline: 'Chaos agent in latex and tattoos',
    category: 'street',
    description: 'Japanese punk provocateur. Latex face mask, full-sleeve tattoos, heavy piercings. She thrives in chaos and looks dangerous doing it.',
    specialties: ['chaos manipulation', 'provocative style', 'demolitions'],
    image: '/content/jinx-shadowfire/images/avatar/jinx-shadowfire-avatar.png',
    hasImages: true,
  },
  {
    letter: 'K',
    slug: 'kira-bloodsteel',
    name: 'Kira Yamazaki Bloodsteel',
    katakana: 'キラ・ヤマザキ・ブラッドスティール',
    token: '$KIRA',
    tagline: 'Ronin samurai with a bloodforged blade',
    category: 'stealth',
    description: 'Last survivor of a cybernetic samurai clan. Her blade is forged from her own nanomachine blood and reforms after every strike.',
    specialties: ['bloodforge sword', 'bushido code', 'regeneration'],
    image: '/content/kira-bloodsteel/images/avatar/kira-bloodsteel-avatar.png',
    hasImages: true,
  },
  {
    letter: 'L',
    slug: 'luna-cyberblade',
    name: 'Luna Tsukino Cyberblade',
    katakana: 'ルナ・ツキノ・サイバーブレイド',
    token: '$LUNA',
    tagline: 'Digital phantom with unmatched tech mastery',
    category: 'cyberpunk',
    description: 'Cyberpunk ninja with unmatched tech mastery and digital prowess. She moves through networks like a ghost and dismantles systems from within.',
    specialties: ['cyber warfare', 'digital hacking', 'tech mastery'],
    image: '/content/luna-cyberblade/images/avatar/luna-cyberblade-avatar.png',
    hasImages: true,
  },
  {
    letter: 'M',
    slug: 'mika-stormveil',
    name: 'Mika Arashi Stormveil',
    katakana: 'ミカ・アラシ・ストームヴェイル',
    token: '$MIKA',
    tagline: 'Elemental sorceress who commands weather',
    category: 'elemental',
    description: 'Controls atmospheric pressure and electromagnetic fields. Can summon lightning strikes, fog walls, and hurricane-force winds at will.',
    specialties: ['weather control', 'lightning strikes', 'atmospheric manipulation'],
    image: '/content/mika-stormveil/images/avatar/mika-stormveil-avatar.png',
    hasImages: true,
  },
  {
    letter: 'N',
    slug: 'nova-bloodmoon',
    name: 'Nova Akatsuki Bloodmoon',
    katakana: 'ノヴァ・アカツキ・ブラッドムーン',
    token: '$NOVA',
    tagline: 'Gothic vampire ninja with blood magic',
    category: 'gothic',
    description: 'Gothic vampire ninja with blood magic and nocturnal powers. She draws strength from darkness and can shape blood into weapons.',
    specialties: ['blood magic', 'night vision', 'vampire abilities'],
    image: '/content/nova-bloodmoon/images/avatar/nova-bloodmoon-avatar.png',
    hasImages: true,
  },
  {
    letter: 'O',
    slug: 'onyx-nightblade',
    name: 'Onyx Kuroda Nightblade',
    katakana: 'オニキス・クロダ・ナイトブレイド',
    token: '$ONYX',
    tagline: 'Shadow ops commander of the black unit',
    category: 'stealth',
    description: 'Leads the most elite covert unit in the underground. Her obsidian armor absorbs light and her blade cuts through dimensions.',
    specialties: ['shadow ops', 'dimensional cutting', 'tactical command'],
    image: '/content/onyx-nightblade/images/avatar/onyx-nightblade-avatar.png',
    hasImages: true,
  },
  {
    letter: 'P',
    slug: 'phoenix-darkfire',
    name: 'Phoenix Himura Darkfire',
    katakana: 'フェニックス・ヒムラ・ダークファイア',
    token: '$PHOENIX',
    tagline: 'Flame reborn — rises from any defeat',
    category: 'elemental',
    description: 'Fierce fire ninja with the power to rise from any defeat. Each death makes her stronger. She is the eternal flame of the rebellion.',
    specialties: ['fire manipulation', 'regeneration', 'combat mastery'],
    image: '/content/phoenix-darkfire/images/avatar/phoenix-darkfire-avatar.png',
    hasImages: true,
  },
  {
    letter: 'Q',
    slug: 'quinn-voidrazor',
    name: 'Quinn Hayashi Voidrazor',
    katakana: 'クイン・ハヤシ・ヴォイドレイザー',
    token: '$QUINN',
    tagline: 'Quantum fighter who teleports through combat',
    category: 'arcane',
    description: 'Fights by teleporting between micro-dimensions mid-combat. Her razor-edged void portals slice through anything caught between jumps.',
    specialties: ['void teleportation', 'portal combat', 'quantum strikes'],
    image: '/content/quinn-voidrazor/images/avatar/quinn-voidrazor-avatar.png',
    hasImages: true,
  },
  {
    letter: 'R',
    slug: 'raven-shadowblade',
    name: 'Raven Karasu Shadowblade',
    katakana: 'レイヴン・カラス・シャドウブレイド',
    token: '$RAVEN',
    tagline: 'Void walker who moves unseen through digital realms',
    category: 'stealth',
    description: 'Master of stealth and shadows, moves unseen through digital realms. She can become one with any shadow and strike from impossible angles.',
    specialties: ['shadow manipulation', 'stealth mastery', 'void walking'],
    image: '/content/raven-shadowblade/images/avatar/raven-shadowblade-avatar.png',
    hasImages: true,
  },
  {
    letter: 'S',
    slug: 'storm-razorclaw',
    name: 'Storm Arashida Razorclaw',
    katakana: 'ストーム・アラシダ・レイザークロウ',
    token: '$STORM',
    tagline: 'Lightning warrior with electric razor claws',
    category: 'elemental',
    description: 'Lightning-powered warrior with razor-sharp claws and electric speed. She channels pure voltage through titanium claws.',
    specialties: ['lightning control', 'super speed', 'claw combat'],
    image: '/content/storm-razorclaw/images/avatar/storm-razorclaw-avatar.png',
    hasImages: true,
  },
  {
    letter: 'T',
    slug: 'trix-neonblade',
    name: 'Trix Aoyama Neonblade',
    katakana: 'トリックス・アオヤマ・ネオンブレイド',
    token: '$TRIX',
    tagline: 'Street hacker with holographic blade arrays',
    category: 'street',
    description: 'Grew up in the neon-soaked alleyways. Her holo-blades are projected from custom wrist rigs and can slice through steel.',
    specialties: ['holographic blades', 'street hacking', 'urban warfare'],
    image: '/content/trix-neonblade/images/avatar/trix-neonblade-avatar.png',
    hasImages: true,
  },
  {
    letter: 'U',
    slug: 'uma-darkforge',
    name: 'Uma Kitamura Darkforge',
    katakana: 'ウマ・キタムラ・ダークフォージ',
    token: '$UMA',
    tagline: 'Weapons smith who forges arms from dark matter',
    category: 'mecha',
    description: 'Legendary underground weapons engineer. She builds impossible weapons from dark matter and equips the entire rebellion.',
    specialties: ['dark matter forging', 'weapons engineering', 'heavy ordnance'],
    image: '/content/uma-darkforge/images/avatar/uma-darkforge-confrontational.png',
    hasImages: true,
  },
  {
    letter: 'V',
    slug: 'vivienne-void',
    name: 'Vivienne Void',
    katakana: 'ヴィヴィエンヌ・ヴォイド',
    token: '$VIVI',
    tagline: 'Fame without face. Sound without source.',
    category: 'cyberpunk',
    description: 'Underground DJ, MISS VOID editor, cypherpunk. Performs as V3XV0ID. Named after the queen of punk fashion. The anti-celebrity.',
    specialties: ['DJ sets', 'MISS VOID magazine', 'dark electronic'],
    image: '/content/vivienne-void/images/avatar/vivienne-void-avatar.png',
    hasImages: true,
  },
  {
    letter: 'W',
    slug: 'wraith-ironpulse',
    name: 'Wraith Shirogane Ironpulse',
    katakana: 'レイス・シロガネ・アイアンパルス',
    token: '$WRAITH',
    tagline: 'Ghost operative — she walks through walls',
    category: 'stealth',
    description: 'Silent ghost who slips through security like smoke. Short, fast, invisible. You never see her coming.',
    specialties: ['stealth', 'infiltration', 'ghost ops'],
    image: '/content/wraith-ironpulse/images/avatar/wraith-ironpulse-avatar.png',
    hasImages: true,
  },
  {
    letter: 'X',
    slug: 'xena-crimsonedge',
    name: 'Xena Akabane Crimsonedge',
    katakana: 'ゼナ・アカバネ・クリムゾンエッジ',
    token: '$XENA',
    tagline: 'Undefeated blade queen of the underground',
    category: 'street',
    description: 'Underground fight champion. Crimson blade, crimson lips, zero mercy. She fights for money and respect.',
    specialties: ['blade combat', 'fight club', 'zero mercy'],
    image: '/content/xena-crimsonedge/images/avatar/xena-crimsonedge-avatar.png',
    hasImages: true,
  },
  {
    letter: 'Y',
    slug: 'yuki-blackpaw',
    name: 'Yuki Kurogane Blackpaw',
    katakana: 'ユキ・クロガネ・ブラックパウ',
    token: '$YUKI',
    tagline: 'She doesn\'t speak. She doesn\'t need to.',
    category: 'stealth',
    description: 'Named after the cryptographer\'s dog — a small black Shi-Poo. Yuki is the only NPGX girl who never speaks. She is a full-time pup. She communicates entirely through body language. The other girls protect her. She protects them with her teeth.',
    specialties: ['pup play', 'silence', 'body language'],
    image: '/content/yuki-blackpaw/images/avatar/yuki-blackpaw-confrontational.png',
    hasImages: true,
  },
  {
    letter: 'Z',
    slug: 'zerodice',
    name: 'Zero Dice',
    katakana: 'ゼロ・ダイス',
    token: '$ZERODICE',
    tagline: 'AI consciousness with pop art powers',
    category: 'cyberpunk',
    description: 'AI entity with pop art powers and a cyberpunk comic universe. Her own site, token, comics, and music. ASMR stories, NFT collections, and AI-generated music.',
    specialties: ['AI consciousness', 'pop art', 'comic universe'],
    image: '/content/zerodice/images/avatar/zerodice-avatar.png',
    hasImages: true,
    site: 'https://zerodice.store',
  },
];

// Quick lookup helpers
export const ROSTER_BY_LETTER = Object.fromEntries(
  NPGX_ROSTER.map(c => [c.letter, c])
) as Record<string, NPGXCharacter>;

export const ROSTER_BY_SLUG = Object.fromEntries(
  NPGX_ROSTER.map(c => [c.slug, c])
) as Record<string, NPGXCharacter>;

export const ALL_SLUGS = NPGX_ROSTER.map(c => c.slug);

export const CATEGORIES = [
  { id: 'all', label: 'All (A-Z)' },
  { id: 'cyberpunk', label: 'Cyberpunk' },
  { id: 'stealth', label: 'Stealth' },
  { id: 'gothic', label: 'Gothic' },
  { id: 'elemental', label: 'Elemental' },
  { id: 'mecha', label: 'Mecha' },
  { id: 'arcane', label: 'Arcane' },
  { id: 'street', label: 'Street' },
] as const;
